/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.IOException;

import javax.swing.JOptionPane;

import dao.DaoImplHibernate;
import dao.DaoImplMongoDB;
import view.ShopView;
import model.Employee;
import utils.Constants;

/**
 *
 * @author gerar
 */
public class LoginView extends javax.swing.JFrame {

    private int counterErrorLogin = 0;
    
    /**
     * Creates new form MiVentana
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloNumeroEmpleado = new javax.swing.JLabel();
        CampoNumeroEmpleado = new javax.swing.JTextField();
        TituloPassword = new javax.swing.JLabel();
        CampoPassword = new javax.swing.JTextField();
        BotonLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloNumeroEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TituloNumeroEmpleado.setText("Número de empleado");

        CampoNumeroEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNumeroEmpleado(evt);
            }
        });

        TituloPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TituloPassword.setText("Password");

        CampoPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPassword(evt);
            }
        });

        BotonLogin.setText("Acceder");
        BotonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					BotonLoginActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CampoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TituloPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(CampoNumeroEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(TituloNumeroEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonLogin)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(TituloNumeroEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoNumeroEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(TituloPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(BotonLogin)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNumeroEmpleado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNumeroEmpleado

    }//GEN-LAST:event_CampoNumeroEmpleado

    private void CampoPassword(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPassword
        
    }//GEN-LAST:event_CampoPassword

    
    private void BotonLoginActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
        int numeroEmpleado;
        String password;

        try {
            numeroEmpleado = Integer.parseInt(CampoNumeroEmpleado.getText());
            password = CampoPassword.getText();

            if (password.isEmpty()) {
                JOptionPane.showMessageDialog(null, "La contraseña es obligatoria.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            DaoImplMongoDB dao = new DaoImplMongoDB();
            dao.connect();

            Employee employee = dao.getEmployee(numeroEmpleado, password);

            dao.disconnect();

            if (employee != null) {
                // Inicio de sesión exitoso, abrir la vista de tienda
                ShopView shop = new ShopView();
                shop.setExtendedState(NORMAL);
                shop.setVisible(true);
                dispose();  // Cerrar la ventana LoginView cuando se accede correctamente
            } else {
                // Credenciales incorrectas, mostrar mensaje de error
                counterErrorLogin++;
                if (counterErrorLogin >= Constants.MAX_LOGIN_TIMES) {
                    JOptionPane.showMessageDialog(null, "Ha superado el número máximo de intentos. La aplicación se cerrará.", "Error intentos", JOptionPane.ERROR_MESSAGE);
                    dispose();  // Cerrar la ventana LoginView si se supera el límite de intentos
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario o password incorrectos", "Error login", JOptionPane.ERROR_MESSAGE);
                    CampoNumeroEmpleado.setText("");
                    CampoPassword.setText("");
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El número de empleado debe ser un número entero válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonLogin;
    private javax.swing.JTextField CampoNumeroEmpleado;
    private javax.swing.JTextField CampoPassword;
    private javax.swing.JLabel TituloNumeroEmpleado;
    private javax.swing.JLabel TituloPassword;
    // End of variables declaration//GEN-END:variables
}
